version: '3.11.5'

services:
  myfastapi:
    build: .
    container_name: MyFastAPI
    # command: python main.py runserver 0.0.0.0:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    environment:
      - POSTGRES_DB=hw02
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=567234

    container_name: postgresql
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pgdata:
